### PR TITLE
Support api port configuration

### PR DESCRIPTION
**Pull request by lornasong**
- Add new `port` config at top-level
 - Update api to consume new port config
 - Update e2e test config to dynamically choose next free port
 - Fix a controller test to dynamically choose next free port

### CODE REVIEW

**Review by findkim — COMMENTED** [review]
The code looks good. Just wanted to double check about the API, are we requiring that the consul-terraform-sync daemon will require and always bind to a port?

**Comment by lornasong** [comment]
@findkim thanks for asking! Currently the daemon will always bind to a port i.e. it will always serve the api at the default or configured port. Are you thinking maybe have it be an option to serve the api or not?

**Comment by findkim** [comment]
Ok! Just wanted to double check. I had considered optional API for a bit when we had imagined it to be a purely daemon process. But I think the project has already evolved quickly that it's probably the common case to have the API enabled.

**Review by findkim — APPROVED** [review]

**Comment by lornasong** [comment]
I had also imagined that it would be common case but I think it's a good question to raise. I'll go ahead and merge for now - thank you for reviewing! But I'll bring it up for team discussion and we can add a disable/enable option later.

**Pull request merged**
